### PR TITLE
psr-4 fix

### PR DESCRIPTION
**Pull request by kaloczikvn**

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @kaloczikvn 

Thank you very much for your contributions. 

Please take in mind I will making a major breaking change into this repository when launching v2 that is completely incompatible with the current version (that still not finished and will never be) .

I will merge this, but I don't think it makes sense to continue pushing fixes in this branch. 

Thanks again,
Pedro

**Comment by kaloczikvn** [comment]
Hey,

I might push some minor tweaks here and there because we probably gonna use it in one of our production system.

Hows v2 gonna differ from the current version? It is already much better than the https://github.com/Laravel-Backpack/Settings thats why we love using it!

Keep up the good work!

Thanks,
Kevin

**Comment by pxpm** [comment]
Hello @kaloczikvn 

The v2 would drop the dependency on seeders and use a file `class` to handle the panels. Settings and Panels would become classes so you could do stuff like this:

```php
Bpsettings::panel('your_panel_name')
    ->settings(
        Settings::type('text')->name('setting_name')->access(function() { return backpack_user()->hasRole('admin') }, 
        Setting:type('color')->name('setting_name_2')
    )->wrapper('this wrapper would be applied to all settings inside the panel')
```

A lot of stuff is already implemented, but I'v been very busy fixing Backpack underlaying problems and didn't give too much atention into my packages.

I will try to find sometime to clean up some stuff and publish this v2, maybe you find it even better and your contributions would help me alot :)

Thanks again!

Pedro

**Comment by o15a3d4l11s2** [comment]
Just a note that I am also interested in this package.

**Pull request merged**
